import type { NextPage } from 'next'
import { imageOptimizer } from 'next/dist/server/image-optimizer'
import Head from 'next/head'
import Image from 'next/image'
import { Link as ScrollLink } from 'react-scroll'
import CardAbout from '../components/CardAbout'
import CardValue from '../components/CardValue'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Yoshida Profile</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}

        {/* favicon追加 */}
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/favicons/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicons/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicons/site.webmanifest" />
        <link
          rel="mask-icon"
          href="/favicons/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>

      <header>
        <div className="justify-between p-2 md:flex">
          <div className="text-center">
            <Image
              src="/images/logo.png"
              alt="logo"
              width={120}
              height={60}
              // layout="fill"
              objectFit="contain"
            />
          </div>
          <div className="my-auto flex justify-center text-sm font-medium text-[#008c8d] md:text-base">
            <ScrollLink
              to="about"
              className="mx-2 hover:cursor-pointer hover:opacity-50 md:mx-4"
              smooth={true}
              duration={300}
            >
              ABOUT
            </ScrollLink>
            <ScrollLink
              to="skills"
              className="mx-2 hover:cursor-pointer hover:opacity-50 md:mx-4"
              smooth={true}
              duration={300}
            >
              SKILLS
            </ScrollLink>
            <ScrollLink
              to="values"
              className="mx-2 hover:cursor-pointer hover:opacity-50 md:mx-4"
              smooth={true}
              duration={300}
            >
              VALUES
            </ScrollLink>
            <ScrollLink
              to="future"
              className="mx-2 hover:cursor-pointer hover:opacity-50 md:mx-4"
              smooth={true}
              duration={300}
            >
              FUTURE
            </ScrollLink>
            {/* <Link href="#skills">
            <a className="mx-2 md:mx-4">SKILLS</a>
          </Link>
          <Link href="#values">
            <a className="mx-2 md:mx-4">VALUES</a>
          </Link>
          <Link href="#future">
            <a className="mx-2 md:mx-4">FUTURE</a>
          </Link> */}
          </div>
        </div>
      </header>
      <main>
        <section className="bg-[#6bc2c3]">
          <div className="justify-between p-5 text-center md:flex">
            <div className="md:my-auto md:ml-20 md:text-left">
              <h1 className="text-2xl font-bold tracking-widest text-white md:text-4xl">
                YOSHIDA TATSUYA
              </h1>
              <p className="my-3 text-base tracking-widest text-white md:text-2xl">
                自己紹介
              </p>
            </div>
            <div className="px-10 md:p-10 md:text-right">
              <Image
                src="/images/hero.png"
                alt="hero"
                width={585}
                height={498}
              />
            </div>
          </div>
        </section>
        <section
          id="about"
          className="w-full bg-cover md:bg-about md:pt-10 md:pb-36"
        >
          <div className="mx-auto justify-center py-6 text-center md:flex">
            <p className="text-xl font-bold tracking-widest md:text-3xl">
              私について
            </p>
            <p className="items-center pl-2 text-sm text-[#008c8d] md:flex md:text-base">
              ABOUT
            </p>
          </div>
          <div className="mx-auto max-w-screen-lg justify-center md:flex">
            <CardAbout
              image="/images/about-1.png"
              subheading="趣味"
              text="映画を見るのが好きです。好きな映画監督はクエンティン・タランティーノです。"
            ></CardAbout>
            <CardAbout
              image="/images/about-2.png"
              subheading="好きな食べ物"
              text="焼きそば、からあげ、うどんが好きです。つまり麺が好きです。つれづれなるまゝに日暮らし硯にむかひて心にうつりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。"
            ></CardAbout>
            <CardAbout
              image="/images/about-3.png"
              subheading="性格"
              text="小心者の内弁慶。つれづれなるまゝに日暮らし硯にむかひて心にうつりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。"
            ></CardAbout>
            {/* SSGの場合 */}
            {/* {allPostsData.map(({ index, image, subheading, text }) => (
              <div key={index} className="mx-auto w-[320px] p-5">
                <div className="text-center">
                  <Image
                    src={image}
                    alt="about"
                    width={184}
                    height={157}
                    // layout="fill"
                    objectFit="contain"
                  />
                </div>
                <p className="text-[#008c8d] font-bold text-xl md:text-2xl text-center my-1 md:my-3">
                  {subheading}
                </p>
                <p className="leading-7">{text}</p>
              </div>
            ))} */}
          </div>
        </section>
        <section
          id="skills"
          className="w-full bg-skillsSp bg-cover py-5 md:-mt-20 md:bg-skills md:py-10"
        >
          <div className="mx-auto max-w-screen-lg justify-center md:flex">
            <div className="my-auto px-10 md:p-10">
              <div className="mx-auto py-4 text-center md:hidden">
                <p className="text-xl font-bold tracking-widest md:text-3xl">
                  スキル
                </p>
                <p className="items-center pl-2 text-sm font-semibold text-[#008c8d] md:flex md:text-base">
                  SKILLS
                </p>
              </div>
              <div className="md:-ml-32">
                <Image
                  src="/images/skill.png"
                  alt="skill"
                  width={535}
                  height={372}
                />
              </div>
            </div>
            <div>
              <div className="mx-auto my-16 px-5 md:max-w-[530px] md:py-5">
                <div className="mx-auto hidden justify-start py-4 text-center md:flex">
                  <p className="text-xl font-bold tracking-widest md:text-3xl">
                    スキル
                  </p>
                  <p className="items-center pl-2 text-sm font-semibold text-[#008c8d] md:flex md:text-base">
                    SKILLS
                  </p>
                </div>
                <p className="text-sm leading-7 md:text-base">
                  つれづれなるまゝに日暮らし硯にむかひて心にうつりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。つれづれなるまゝに日暮らし硯にむかひて心にうつりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。つれづれなるまゝに日暮らし硯にむかひて。
                </p>
                <div className="mt-4 rounded bg-white p-4 md:p-8">
                  <div className="mt-2 first:mt-0">
                    <p className="text-sm font-semibold tracking-wider text-[#008c8d] opacity-80 md:text-base">
                      SKILLSKILL
                    </p>
                    <ul className="flex">
                      <li className="mr-4 w-11/12">
                        <div className="relative pt-1">
                          <div className="flex h-4 overflow-hidden rounded bg-[#c5eaea] text-xs">
                            <div
                              style={{ width: '40%' }}
                              className="flex flex-col justify-center whitespace-nowrap bg-[#2bb9ba] text-center text-white shadow-none"
                            ></div>
                          </div>
                        </div>
                      </li>
                      <li className="w-1/12 text-sm text-[#008c8d] md:text-base">
                        40%
                      </li>
                    </ul>
                  </div>
                  <div className="mt-2 first:mt-0">
                    <p className="text-sm font-semibold tracking-wider text-[#008c8d] opacity-80 md:text-base">
                      SKILLSKILL
                    </p>
                    <ul className="flex">
                      <li className="mr-4 w-11/12">
                        <div className="relative pt-1">
                          <div className="flex h-4 overflow-hidden rounded bg-[#c5eaea] text-xs">
                            <div
                              style={{ width: '40%' }}
                              className="flex flex-col justify-center whitespace-nowrap bg-[#2bb9ba] text-center text-white shadow-none"
                            ></div>
                          </div>
                        </div>
                      </li>
                      <li className="w-1/12 text-sm text-[#008c8d] md:text-base">
                        40%
                      </li>
                    </ul>
                  </div>
                  <div className="mt-2 first:mt-0">
                    <p className="text-sm font-semibold tracking-wider text-[#008c8d] opacity-80 md:text-base">
                      SKILLSKILL
                    </p>
                    <ul className="flex">
                      <li className="mr-4 w-11/12">
                        <div className="relative pt-1">
                          <div className="flex h-4 overflow-hidden rounded bg-[#c5eaea] text-xs">
                            <div
                              style={{ width: '40%' }}
                              className="flex flex-col justify-center whitespace-nowrap bg-[#2bb9ba] text-center text-white shadow-none"
                            ></div>
                          </div>
                        </div>
                      </li>
                      <li className="w-1/12 text-sm text-[#008c8d] md:text-base">
                        40%
                      </li>
                    </ul>
                  </div>
                  <div className="mt-2 first:mt-0">
                    <p className="text-sm font-semibold tracking-wider text-[#008c8d] opacity-80 md:text-base">
                      SKILLSKILL
                    </p>
                    <ul className="flex">
                      <li className="mr-4 w-11/12">
                        <div className="relative pt-1">
                          <div className="flex h-4 overflow-hidden rounded bg-[#c5eaea] text-xs">
                            <div
                              style={{ width: '40%' }}
                              className="flex flex-col justify-center whitespace-nowrap bg-[#2bb9ba] text-center text-white shadow-none"
                            ></div>
                          </div>
                        </div>
                      </li>
                      <li className="w-1/12 text-sm text-[#008c8d] md:text-base">
                        40%
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="values">
          <div className="mx-auto justify-center py-6 text-center md:flex">
            <p className="text-xl font-bold tracking-widest md:text-3xl">
              価値観
            </p>
            <p className="items-center pl-2 text-sm text-[#008c8d] md:flex md:text-base">
              VALUE
            </p>
          </div>
          <div>
            <div className="mx-auto max-w-screen-lg">
              <div className="relative mx-5 justify-center divide-[#c5eaea] rounded-lg bg-white md:flex md:divide-x-2 md:px-5 md:py-10">
                <CardValue title="価値観00" image="/images/value1.png">
                  つれづれなるまりゆくよしなし事をそこはかとなく書きつくればつれづれなるまりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。
                </CardValue>
                <CardValue title="価値観02" image="/images/value2.png">
                  つれづれなるまりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。
                </CardValue>
                <CardValue title="価値観03" image="/images/value3.png">
                  つれづれなるまりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。
                </CardValue>
              </div>
            </div>
          </div>
        </section>
        <section
          id="future"
          className="-mt-64 w-full bg-futureSp bg-cover pt-64 md:bg-future"
        >
          <div className="mx-auto mt-5 max-w-screen-lg justify-center pt-8 md:flex md:py-12">
            <div className="mx-5 md:max-w-[480px]">
              <div className="mx-auto justify-start text-center md:flex">
                <p className="text-xl font-bold tracking-widest md:text-3xl">
                  3年後にやりたいこと
                </p>
                <p className="items-center pl-2 text-sm font-semibold text-[#008c8d] md:flex md:text-base">
                  FUTURE
                </p>
              </div>
              <p className="mt-8 text-sm leading-7 md:text-base md:leading-7">
                つれづれなるまゝに日暮らし硯にむかひて心にうつりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。つれづれなるまゝに日暮らし硯にむかひて心にうつりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。つれづれなるまゝに日暮らし硯にむかひて。
              </p>
            </div>
            <div className="mt-5 -mb-1 md:mx-5 md:my-0">
              <div className="">
                <Image
                  src="/images/future.png"
                  alt="skill"
                  width={480}
                  height={251}
                />
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-[#262c3a] text-white">
        <div className="mx-auto max-w-screen-lg p-4 md:p-8">
          <div className="my-2">
            <ul className="flex flex-wrap justify-center text-xs font-extralight opacity-75 md:hidden">
              <li className="m-2">お問い合わせ</li>
              <li className="m-2">助成金について</li>
              <li className="m-2">特定商取引法に基づく表記</li>
              <li className="m-2">プライバシーポリシー</li>
            </ul>
          </div>
          <div className="my-5">
            <ul className="hidden justify-center md:flex">
              <li className="my-auto mr-3 text-xs tracking-widest">
                CREATED BY
              </li>
              <li className="text-lg tracking-wider">吉田 達哉</li>
            </ul>
          </div>
          <div className="p-5 text-center md:p-10">
            <Image
              src="/images/logo_white.png"
              alt="logo-white"
              width={110}
              height={132}
            />
          </div>
          <div className="flex justify-center">
            <div>
              <Image
                src="/images/twitter.png"
                alt="twitter"
                width={36}
                height={16}
                objectFit="contain"
              />
            </div>
            <div>
              <Image
                src="/images/facebook.png"
                alt="facebook"
                width={36}
                height={16}
                objectFit="contain"
              />
            </div>
          </div>
          <div className="mt-5 text-center text-xs tracking-widest">
            <p>© 2022 RE-END</p>
          </div>
        </div>
      </footer>
    </>
  )
}

export default Home
