import type { NextPage } from 'next'
import { imageOptimizer } from 'next/dist/server/image-optimizer'
import Head from 'next/head'
import Image from 'next/image'
import { Link as ScrollLink } from 'react-scroll'
import CardAbout from '../components/CardAbout'
import CardValue from '../components/CardValue'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Yoshida Profile</title>
        <meta name="description" content="Generated by create next app" />

        {/* favicon追加 */}
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/favicons/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicons/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicons/site.webmanifest" />
        <link
          rel="mask-icon"
          href="/favicons/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>

      <header>
        <div className="justify-between p-2 md:flex">
          <div className="text-center">
            <Image
              src="/images/logo.png"
              alt="logo"
              width={120}
              height={60}
              // layout="fill"
              objectFit="contain"
            />
          </div>
          <div className="my-auto flex justify-center text-sm font-medium text-[#008c8d] md:text-base">
            <ScrollLink
              to="about"
              className="mx-2 hover:cursor-pointer hover:opacity-50 md:mx-4"
              smooth={true}
              duration={300}
            >
              ABOUT
            </ScrollLink>
            <ScrollLink
              to="skills"
              className="mx-2 hover:cursor-pointer hover:opacity-50 md:mx-4"
              smooth={true}
              duration={300}
            >
              SKILLS
            </ScrollLink>
            <ScrollLink
              to="values"
              className="mx-2 hover:cursor-pointer hover:opacity-50 md:mx-4"
              smooth={true}
              duration={300}
            >
              VALUES
            </ScrollLink>
            <ScrollLink
              to="future"
              className="mx-2 hover:cursor-pointer hover:opacity-50 md:mx-4"
              smooth={true}
              duration={300}
            >
              FUTURE
            </ScrollLink>
          </div>
        </div>
      </header>
      <main>
        <section className="bg-[#6bc2c3]">
          <div className="justify-between p-5 text-center md:flex">
            <div className="md:my-auto md:ml-20 md:text-left">
              <h1 className="text-2xl font-bold tracking-widest text-white md:text-4xl">
                YOSHIDA TATSUYA
              </h1>
              <p className="my-3 text-base font-semibold tracking-widest text-white opacity-70 md:text-2xl">
                吉田 達哉
              </p>
            </div>
            <div className="px-10 md:p-10 md:text-right">
              <Image
                src="/images/hero.png"
                alt="hero"
                width={585}
                height={498}
              />
            </div>
          </div>
        </section>
        <section
          id="about"
          className="w-full bg-cover md:bg-about md:pt-10 md:pb-36"
        >
          <div className="mx-auto justify-center py-6 text-center md:flex">
            <p className="text-xl font-bold tracking-widest md:text-3xl">
              私について
            </p>
            <p className="items-center pl-2 text-sm font-semibold text-[#008c8d] md:flex md:text-base">
              ABOUT
            </p>
          </div>
          <div className="mx-auto max-w-screen-lg justify-center md:flex">
            <CardAbout
              image="/images/about-1.png"
              subheading="趣味"
              text="映画や美術館、古い家具などが好き。自然の中で過ごしたり、体を動かすことも好き。おうち時間では料理やプラモデルにもハマりつつあります。"
            ></CardAbout>
            <CardAbout
              image="/images/about-2.png"
              subheading="好きな食べ物"
              text="うどん、焼きそば、パスタなど、とにかく麺が好き。それとモスバーガーを愛しています。チョコ菓子やスイーツなど甘いものも好き。"
            ></CardAbout>
            <CardAbout
              image="/images/about-3.png"
              subheading="性格"
              text="好奇心強めで、少しこだわりがあって、ちょっとドライで、協調性があって、かなり繊細で、考えすぎない、心配性です！"
            ></CardAbout>
          </div>
        </section>
        <section
          id="skills"
          className="w-full bg-skillsSp bg-cover py-5 md:-mt-20 md:bg-skills md:py-10"
        >
          <div className="mx-auto max-w-screen-lg justify-center md:flex">
            <div className="my-auto px-10 md:p-10">
              <div className="mx-auto py-4 text-center md:hidden">
                <p className="text-xl font-bold tracking-widest md:text-3xl">
                  スキル
                </p>
                <p className="items-center pl-2 text-sm font-semibold text-[#008c8d] md:flex md:text-base">
                  SKILLS
                </p>
              </div>
              <div className="md:-ml-32">
                <Image
                  src="/images/skill.png"
                  alt="skill"
                  width={535}
                  height={372}
                />
              </div>
            </div>
            <div>
              <div className="mx-auto my-16 px-5 md:max-w-[530px] md:py-5">
                <div className="mx-auto hidden justify-start py-4 text-center md:flex">
                  <p className="text-xl font-bold tracking-widest md:text-3xl">
                    スキル
                  </p>
                  <p className="items-center pl-2 text-sm font-semibold text-[#008c8d] md:flex md:text-base">
                    SKILLS
                  </p>
                </div>
                <p className="text-sm leading-7 md:text-base">
                  杉並区在住のデザイナー。メーカーでインテリアの商品企画・開発を担当。現在は、ベンチャー企業でサイトのデザインやイベントの運用・販促関連を担当。その他、3Dモデリング、CAD設計、パッケージデザインも経験。機械学習への興味からプログラミングスクールを修了。2022年にE資格を取得。
                </p>
                <div className="mt-4 rounded bg-white p-4 md:p-8">
                  <div className="mt-2 first:mt-0">
                    <p className="text-sm font-semibold tracking-wider text-[#008c8d] opacity-80 md:text-base">
                      3D design
                    </p>
                    <ul className="flex">
                      <li className="mr-4 w-11/12">
                        <div className="relative pt-1">
                          <div className="flex h-4 overflow-hidden rounded bg-[#c5eaea] text-xs">
                            <div
                              style={{ width: '60%' }}
                              className="flex flex-col justify-center whitespace-nowrap bg-[#2bb9ba] text-center text-white shadow-none"
                            ></div>
                          </div>
                        </div>
                      </li>
                      <li className="w-1/12 text-sm text-[#008c8d] md:text-base">
                        60%
                      </li>
                    </ul>
                  </div>
                  <div className="mt-2 first:mt-0">
                    <p className="text-sm font-semibold tracking-wider text-[#008c8d] opacity-80 md:text-base">
                      2D design
                    </p>
                    <ul className="flex">
                      <li className="mr-4 w-11/12">
                        <div className="relative pt-1">
                          <div className="flex h-4 overflow-hidden rounded bg-[#c5eaea] text-xs">
                            <div
                              style={{ width: '20%' }}
                              className="flex flex-col justify-center whitespace-nowrap bg-[#2bb9ba] text-center text-white shadow-none"
                            ></div>
                          </div>
                        </div>
                      </li>
                      <li className="w-1/12 text-sm text-[#008c8d] md:text-base">
                        20%
                      </li>
                    </ul>
                  </div>
                  <div className="mt-2 first:mt-0">
                    <p className="text-sm font-semibold tracking-wider text-[#008c8d] opacity-80 md:text-base">
                      Programming
                    </p>
                    <ul className="flex">
                      <li className="mr-4 w-11/12">
                        <div className="relative pt-1">
                          <div className="flex h-4 overflow-hidden rounded bg-[#c5eaea] text-xs">
                            <div
                              style={{ width: '5%' }}
                              className="flex flex-col justify-center whitespace-nowrap bg-[#2bb9ba] text-center text-white shadow-none"
                            ></div>
                          </div>
                        </div>
                      </li>
                      <li className="w-1/12 text-sm text-[#008c8d] md:text-base">
                        5%
                      </li>
                    </ul>
                  </div>
                  <div className="mt-2 first:mt-0">
                    <p className="text-sm font-semibold tracking-wider text-[#008c8d] opacity-80 md:text-base">
                      Machine learning
                    </p>
                    <ul className="flex">
                      <li className="mr-4 w-11/12">
                        <div className="relative pt-1">
                          <div className="flex h-4 overflow-hidden rounded bg-[#c5eaea] text-xs">
                            <div
                              style={{ width: '15%' }}
                              className="flex flex-col justify-center whitespace-nowrap bg-[#2bb9ba] text-center text-white shadow-none"
                            ></div>
                          </div>
                        </div>
                      </li>
                      <li className="w-1/12 text-sm text-[#008c8d] md:text-base">
                        15%
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="values">
          <div className="mx-auto justify-center py-6 text-center md:flex">
            <p className="text-xl font-bold tracking-widest md:text-3xl">
              価値観
            </p>
            <p className="items-center  pl-2 text-sm font-semibold  text-[#008c8d] md:flex md:text-base">
              VALUES
            </p>
          </div>
          <div>
            <div className="mx-auto max-w-screen-lg">
              <div className="relative mx-5 justify-center divide-[#c5eaea] rounded-lg bg-white md:flex md:divide-x-2 md:px-5 md:py-10">
                <CardValue title="上機嫌でいる" image="/images/value1.png">
                  この世界の最大の罪は不機嫌。不機嫌は伝染し、運を遠ざける。なによりも機嫌よくいること。そんなところに幸運は訪れる。
                </CardValue>
                <CardValue title="隣の人を助ける" image="/images/value2.png">
                  神様は隣の人に電話をかけてきている。隣の人を助ければ神様に出会える。遠くの誰かではなく、まずは目の前の人を大切にする。
                </CardValue>
                <CardValue
                  title="自らの運命を愛する"
                  image="/images/value3.png"
                >
                  良いことも、悪いことも、嬉しいことも、悲しいことも、全部自分の積み上げてきたもの。全て飲み込んで、自分の命に変える。
                </CardValue>
              </div>
            </div>
          </div>
        </section>
        <section
          id="future"
          className="-mt-64 w-full bg-futureSp bg-cover pt-64 md:bg-future"
        >
          <div className="mx-auto mt-5 max-w-screen-lg justify-center pt-8 md:flex md:py-12">
            <div className="mx-5 md:max-w-[480px]">
              <div className="mx-auto justify-start text-center md:flex">
                <p className="text-xl font-bold tracking-widest md:text-3xl">
                  3年後にやりたいこと
                </p>
                <p className="items-center pl-2 text-sm font-semibold text-[#008c8d] md:flex md:text-base">
                  FUTURE
                </p>
              </div>
              <p className="mt-8 text-sm leading-7 md:text-base md:leading-7">
                まだ大きくはないが、ニッチな分野でじっくりと売り上げ（もしくは認知度）を伸ばし始めている。チームメンバー3〜5人程度で組織している。そろそろ少し知名度のある人や会社との関わりが欲しいところ。しかし、焦らずじっくりとデリケートな分野を攻めていく。{' '}
              </p>
            </div>
            <div className="mt-5 -mb-1 md:mx-5 md:my-0">
              <div className="">
                <Image
                  src="/images/future.png"
                  alt="skill"
                  width={480}
                  height={251}
                />
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-[#262c3a] text-white">
        <div className="mx-auto max-w-screen-lg p-4 md:p-8">
          <div className="my-2">
            <ul className="flex flex-wrap justify-center text-xs font-extralight opacity-75 md:hidden">
              <li className="m-2">お問い合わせ</li>
              <li className="m-2">助成金について</li>
              <li className="m-2">特定商取引法に基づく表記</li>
              <li className="m-2">プライバシーポリシー</li>
            </ul>
          </div>
          <div className="my-5">
            <ul className="hidden justify-center md:flex">
              <li className="my-auto mr-3 text-xs tracking-widest">
                CREATED BY
              </li>
              <li className="text-lg tracking-wider">吉田 達哉</li>
            </ul>
          </div>
          <div className="p-5 text-center md:p-10">
            <Image
              src="/images/logo_white.png"
              alt="logo-white"
              width={110}
              height={132}
            />
          </div>
          <div className="flex justify-center">
            <div>
              <Image
                src="/images/twitter.png"
                alt="twitter"
                width={36}
                height={16}
                objectFit="contain"
              />
            </div>
            <div>
              <Image
                src="/images/facebook.png"
                alt="facebook"
                width={36}
                height={16}
                objectFit="contain"
              />
            </div>
          </div>
          <div className="mt-5 text-center text-xs tracking-widest">
            <p>© 2022 RE-END</p>
          </div>
        </div>
      </footer>
    </>
  )
}

export default Home
